### ISSUE TITLE
Crash when starting preferences

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Rolzad73/droid2600#3]
```
Automated crash report from developer console:

v15, v16
Jan 19, 2011 11:06:00 AM
0 reports/week 



java.util.UnknownFormatConversionException: Conversion is ''
at java.util.Formatter$FormatSpecifierParser.advance(Formatter.java:2641)
at 
java.util.Formatter$FormatSpecifierParser.parseConversionType(Formatter.java:271
6)
at 
java.util.Formatter$FormatSpecifierParser.parseArgumentIndexAndFlags(Formatter.j
ava:2687)
at 
java.util.Formatter$FormatSpecifierParser.parseFormatToken(Formatter.java:2624)
at java.util.Formatter.doFormat(Formatter.java:1072)
at java.util.Formatter.format(Formatter.java:994)
at java.lang.String.format(String.java:2254)
at java.lang.String.format(String.java:2219)
at android.preference.ListPreference.getSummary(ListPreference.java:152)
at android.preference.Preference.onBindView(Preference.java:441)
at android.preference.Preference.getView(Preference.java:391)
at 
android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:22
1)
at android.widget.AbsListView.obtainView(AbsListView.java:1361)
at android.widget.ListView.makeAndAddView(ListView.java:1743)
at android.widget.ListView.fillDown(ListView.java:668)
at android.widget.ListView.fillFromTop(ListView.java:725)
at android.widget.ListView.layoutChildren(ListView.java:1596)
at android.widget.AbsListView.onLayout(AbsListView.java:1174)
at android.view.View.layout(View.java:7077)
at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
at android.view.View.layout(View.java:7077)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1252)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1128)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1045)
at android.view.View.layout(View.java:7077)
at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
at android.view.View.layout(View.java:7077)
at android.view.ViewRoot.performTraversals(ViewRoot.java:1045)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1727)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `diggerb...@gmail.com` on 29 Jan 2011 at 8:30

**Comment by Rolzad73** [comment]
I found that the special character for "%" (aka &#37;) in Skip Frames entries array is somehow the cause of the crash even though there is specified entrie values of integers.

It only crashes when an entry with the special character is currently selected in the list.

While removing the special character stops the crash, working on a proper fix.

**UPDATE:**
% signs are special in Android XML (size defined for example) and some other "escaping" attempts did not work.  In the end, using Unicode &#65285; was the desired solution.
